### ISSUE TITLE
sproto_dump or sprotodump?

### ISSUE THREAD

**Issue by yksalun** [lvzixun/sproto-Csharp#11]
您好，在此工程的.gitmodules文件中看到子模块的链接地址是：https://github.com/lvzixun/sproto_dump.git
而实际上您的sprotodump地址是:https://github.com/lvzixun/sprotodump.git
经测试，两个版本是不一样的，直接访问https://github.com/lvzixun/sproto_dump地址的内容确是https://github.com/lvzixun/sprotodump。可见sprotodump才是您维护的官方版，那此工程是否应该同步到官方版呢？以防bug更新同步？

**Comment by lvzixun** [comment]
`sproto_dump`这个名字是最开始取得，后来经过同事的建议把名字改成了`sprotodump`所以这个submodule应该是忘记改了。 dump的话，以https://github.com/lvzixun/sprotodump.git 为准。 
PS:我待会儿把submodule的链接给改下。 ;)

**Comment by yksalun** [comment]
good girl. :)
