### ISSUE TITLE
关于这个项目和skynet

### ISSUE THREAD

**Issue by gyx9208** [lvzixun/sproto-Csharp#2]
现在版本的skynet，数据包头两个字节是包长度，包总长度会大2。这个sproto的rpc pack没有做这件事。这是你的原意吗？我们需要手动给byte数组再添前两位，是这样吗？

**Comment by lvzixun** [comment]
这个项目是根据云风的 lua版本 [sproto](https://github.com/cloudwu/sproto) 来实现的。包的长度不是sproto序列化所考虑的内容。 而且在lua版本中也并没有做这个事情， 所以这里就跟lua版本保持了一致。

如果用做网络传输的话， 需要额外添加一个包头。

**Comment by gyx9208** [comment]
谢谢
